# Generated by Django 4.2 on 2023-04-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(upload_to='photos/courses')),
                ('course_title', models.CharField(max_length=200)),
                ('course_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
